### ISSUE TITLE
Partial header now function is not defined error

### ISSUE THREAD

**Issue by Tdnshah** [hivickylai/hugo-theme-introduction#12]
I am trying to use this theme and getting 3 error as below:- 
1. ERROR: 2017/08/31 13:13:27 template.go:350: template: theme/partials/header.html:52: function "now" not defined
2. ERROR: 2017/08/31 13:13:27 template.go:119: html/template: "theme/partials/header.html" is an incomplete template in theme/partials/header.html
3. ERROR: 2017/08/31 13:13:27 template.go:119: html/template: "theme/partials/header.html" is an incomplete template in theme/partials/header.html
Also no css is getting applied and loaded so can you please me resolve this as i liked this theme alot a d want to use for my personal blog.

**Comment by Tdnshah** [comment]
This issue was because of my older hugo version... When i updated my hugo to the latest version 0.26 linux it worked form me very well.

**Comment by hivickylai** [comment]
Glad you got it sorted, thanks for commenting back on the issue!
