### ISSUE TITLE
Image styling is off when using dark theme

### ISSUE THREAD

**Issue by Lytigas** [hivickylai/hugo-theme-introduction#19]
When using the dark theme, there is a white (#fff) background surrounding images.
![screenshot_2017-12-28_16-23-33](https://user-images.githubusercontent.com/20375641/34426464-a5c1ba86-ebeb-11e7-9f2b-080494f60d1e.png)

The relevant css is:
`dark-style.css`
```css
.card {
    ...
    background-color: #fff; */
    ...
}
```
If someone could tell me how to PR the css, I'd be glad to handle it. It's also worth noting there are many instances of `background-color: #111` in `dark-style.css`, which seem out of place but AFAIK produce no adverse effects.

**Comment by xnaas** [comment]
I realize this is the incorrect place for this, but did you have to make any other changes to the CSS to get this theme to work at all? On hugo v0.31.1, building the site with light or dark theme simply results in no CSS:

![image](https://user-images.githubusercontent.com/8271327/34448117-48b1e01c-ecb0-11e7-8dce-1e59d5b3fa47.png)

Did you un-minify the CSS? Are you using another version of hugo? Are you using old code for introduction?

**Comment by Lytigas** [comment]
@xnaas I just followed the quick-start guide in the README.

**Comment by xnaas** [comment]
Well fuck me, I have no idea what the Hell is wrong then. :(

Can you verify your Hugo version, if you don't mind?

**Comment by hivickylai** [comment]
@Lytigas Thanks! I have a sass file for the CSS, I can handle that real quick.

@xnaas If you would open a new Issue and detail the steps you went through for installing the theme, I can see about troubleshooting for you. I can't currently replicate your issue.

**Comment by hivickylai** [comment]
CSS fix in
