### ISSUE TITLE
exampleSite builds in Hugo v.0.31 but not in v.0.32.2

### ISSUE THREAD

**Issue by nancym** [hivickylai/hugo-theme-introduction#22]
I tried your lovely theme today with Hugo 0.32.2 and the exampleSite builds with some warnings but nothing is displayed when I look at it at localhost:1313. I found this thread on discourse.gohugo.io, which might be related to what's going on:

[V.0.32.2 fails to generate content where v.0.31.1 works ](https://discourse.gohugo.io/t/v-0-32-2-fails-to-generate-content-where-v-0-31-1-works/9849/13)

bep wrote that he "will release a new version of Hugo tomorrow with, among some others, the relevant fix for this. Your site will, however, not work as expected. This is the index vs _index thing, noted in the release notes."

I'm hoping that your introduction-theme exampleSite will just work with the next release, but want to let you know there might be problems or things you might want to change in this theme so it's more compatible with bundles, etc.

Thanks!

**Comment by penance316** [comment]
I am getting the same issue here with version
Hugo Static Site Generator v0.32.3 darwin/amd64 BuildDate: 2018-01-09T13:41:16Z

**Comment by hivickylai** [comment]
Thank you @nancym for the heads-up!

Is it only the exampleSite that does not build? If you create content that aligns with the new _index structure, is Introduction building with it?

Just sizing up the issue - I appreciate the info!

**Comment by nancym** [comment]
I've only tried your *introduction* theme with its exampleSite and, unfortunately, it's not working with today's release of Hugo v0.32.4. I have not yet figured out bundles so I don't know what to do to get your theme to work 😞. I've been reading [discourse.gohugo.io](https://discourse.gohugo.io/) and other people are having issues too.

Thanks,
𝓷𝓪𝓷𝓬𝔂𝓶 <- made with https://vickylai.io/uni-pretty/

**Comment by quendera** [comment]
I can confirm it does not build exampleSite or content created.

**Comment by mrshannon** [comment]
This issue still persists when using v0.34 and v0.35dev of Hugo.

**Comment by hivickylai** [comment]
Bug was caused by an issue in config.toml where `params.theme` meant to set the css style was interfering with `theme` where Hugo looks for the default theme name.

Updated the example config file and site code to use `themestyle` for choosing the light or dark theme.
