### ISSUE TITLE
Change parameter names to camelCase

### ISSUE THREAD

**Issue by hivickylai** [hivickylai/hugo-theme-introduction#23]
In the exampleSite `config.toml` and throughout the theme, change the parameter names (under `[params]`) to camelCase.

**Comment by danieldiaz14** [comment]
Dibs! I'll do this today.

**Comment by danieldiaz14** [comment]
Hey Vicky, 

Just to make sure I made the changes correctly! Only the parameters names in the config.toml file? I didn't see any other files with parameter names. 

Thank you,

Daniel
![parameters](https://user-images.githubusercontent.com/25696374/35461025-e2205bac-029a-11e8-99e2-42b2dc3b7ab3.JPG)

**Comment by hivickylai** [comment]
@danieldiaz14 Yup! The `config.toml` is where they're all defined. The parameter names are used throughout the theme templates, where they'll also need to be changed so they still work. 

For example see `layouts/blog/list.html` line 7, where `bloghead` is used.

**Comment by danieldiaz14** [comment]
Pull Request sent!

**Comment by hivickylai** [comment]
Completed in #24
