### ISSUE TITLE
Error: While parsing config: (4, 10): unescaped control character U+000A

### ISSUE THREAD

**Issue by abhinavgarg2129** [hivickylai/hugo-theme-introduction#25]
this error comes up when i change the theme to introduction in config file.

**Comment by abhinavgarg2129** [comment]
found the solution, just change all the TAB characters to spaces, 
may use this link http://tabstospaces.com/

**Comment by hivickylai** [comment]
I'm not able to reproduce your error. If you copied the config.toml from exampleSite, there are no tab characters that I can see.
