### ISSUE TITLE
navbar in introHeight=fullheight is half-visible

### ISSUE THREAD

**Issue by darkk** [hivickylai/hugo-theme-introduction#27]
Navbar in `fullheight` is half-visible without scrolling because of `padding-top: 48px` applied to `div#top` because of `class="section"`. I'm not sure what's _the right way_ to fix it in terms of layout, I've just applied ugly hack locally and I don't submit it as a PR :-)

**Comment by hivickylai** [comment]
Good catch. Actually the hero should not be placed inside a class of "section" if I'm using bulma correctly. Fixed now.

It's been in my mind to rewrite the theme files (I've learned lots since coding this theme and now they look a little messy to me ^^;).
