### ISSUE TITLE
Project title with other languages does not work

### ISSUE THREAD

**Issue by Phoenix-Ann** [hivickylai/hugo-theme-introduction#30]
Hi Vicky，I really like the theme you made. I really want to use this theme for a long time, but I do not have a foundation for front-end development
There is a problems that bothers me,it is about the support of the language. 
When I create a new project title in my own language(Traditional Chinese or Simplified Chinese), the project fails to go to the details page.
Can you fix this？

**Comment by hivickylai** [comment]
Hi Phoenix-Ann, can you post the front matter for your project markdown file? It's the part that looks like this:

```
---
title: "Design"
date: 2017-11-13T12:21:16-05:00
image: "img/plant.jpg"
external_link: ""
weight: 2
---
```

**Comment by Phoenix-Ann** [comment]
Hi Vicky，Thank you for your reply.The front matter for my project markdown file as follows

```
---
title: "狌狌"
date: 2018-02-13T16:30:26+08:00
image: "img/qixie/xingxing.jpg"
external_link: ""
weight: 1
---
```

**Comment by hivickylai** [comment]
**Issue:** `%` character from `urlize` on Chinese characters made jQuery unhappy.

**Fix:** `replace` the `%` to empty string.

**Comment by Phoenix-Ann** [comment]
Hi Vicky,this bug reappear in version  997c707.

**Comment by Phoenix-Ann** [comment]
Hi VickyI find this bug appeared in 997c707  again.
