### ISSUE TITLE
Set default for site parameters where parameter not specified in config

### ISSUE THREAD

**Issue by paskal** [hivickylai/hugo-theme-introduction#33]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37674095-11eb30ac-2c83-11e8-822a-b3ca5e00338c.png)

**Comment by hivickylai** [comment]
Hi @paskal. I'm unable to reproduce your issue. Images in markdown have max-width set (please inspect the image [here](https://vickylai.io/introduction/blog/coffee-ipsum/) for an example). Are you working with the latest version of the theme?

Can you please provide some more detail, or a link to your site where this is an issue?

**Comment by paskal** [comment]
Thanks for rapid response! [Post example](https://github.com/paskal/terrty/blob/master/blog/content/2016-11-17-shinken-vs-sensu-vs-icinga2-vs-zabbix.markdown), problem code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

I guess example you're shown have image defined some other way.

**Comment by hivickylai** [comment]
I copied your blog post content and tested it in the theme. I still cannot replicate your issue.

Are you certain that you have the correct theme? Have you made any changes to the CSS?

![screenshot from 2018-03-20 16-11-20](https://user-images.githubusercontent.com/24644237/37680193-8a74335e-2c59-11e8-97b5-899a8793e87f.png)

**Comment by paskal** [comment]
I guess css doesn't render for some reason. Here is how the main page looks like:
![image](https://user-images.githubusercontent.com/712534/37680310-8f035a9a-2c94-11e8-8a8b-e7b708d6e304.png)
I guess some `site.param` might be missing and instead of raising error this theme just silently brokes. Could you please run the theme against my blog as-is to see what I'm seeing?

**Comment by hivickylai** [comment]
Please ensure you've followed the set-up instructions in the [README](https://github.com/hivickylai/hugo-theme-introduction/blob/master/README.md), particularly those for "Configure your site."

**Comment by paskal** [comment]
To achieve that I need to put aside my configuration and rewrite it from scratch based on your configuration. Adding sanity checks for input and defaults in case something is not set require additional effort but will let people like me (who already have working site and looking for a new theme) to try it out without touching configuration. The issue I've linked last have interesting conversation on that matter.
If you're not interested in setting defaults for case someone trying to use this theme with their own configuration file, feel free to resolve this issue.

**Comment by hivickylai** [comment]
Fair. You make a good point about setting defaults.

Perhaps something to note about Hugo themes in general is that their use of config is a strength. Certainly in this one, you're able to change a lot of the front end just by tweaking a few lines in config -
 everything from the CSS dark/light theme style, to whole sections of the page. When I'm trying new themes, I store my current config in a file under a different name, then use the new theme's example config temporarily, so I can see the theme as it was meant to look, without messing anything up. Then if I like the new theme, I just add in any custom parameters I'm using.

I'll look at setting defaults for those parameters where it's possible. Thanks for bringing the case to my attention!

**Comment by hivickylai** [comment]
Thanks very much @paskal !
