### ISSUE TITLE
Pages without section displays incorrect navigation link

### ISSUE THREAD

**Issue by pmviva** [hivickylai/hugo-theme-introduction#38]
Hi, I found that when you are in a page that doesn't belong to any section (about page, 404 page for example) the navigation links are displayed incorrectly.

The template: nav-single.html has the following code:

```
<span class="nav-item">
<a href="/{{ .Section }}">Back to {{ .Section }}</a>
</span>
```
When .Section is empty this generates the following link `<a href="/">Back to </a>`

The fix I think is obvious... If you don't have a section, then don't display a link since you have no section to go back to.

**Comment by hivickylai** [comment]
Merged #39
