### ISSUE TITLE
DRY up navigation

### ISSUE THREAD

**Issue by pmviva** [hivickylai/hugo-theme-introduction#41]
Right now the code isnt very DRY.

You have nav-list.html and nav-single.html that only differs on a link back to section.

Also you have a hardcoded navigatoon in index.html that can be replaced with a nav partial you already have.
If you need different behavior in the navbar for the home page, you can use {{ .IsHome }} to chech whether you are in thehomepage.

**Comment by pmviva** [comment]
I'll submit a pull request with the changes

**Comment by hivickylai** [comment]
Duplicate of #29
