### ISSUE TITLE
Nav component deprecated

### ISSUE THREAD

**Issue by karanrajpal14** [hivickylai/hugo-theme-introduction#42]
The `nav` component has been deprecated and the latest versions of bulma have moved to `navbar`. As a result, `nav-center` doesn't work anymore. 
Look [here][1] and [here][2]

[1]: https://github.com/jgthms/bulma/issues/894
[2]: https://bulma.io/documentation/components/nav/

**Comment by hivickylai** [comment]
Duplicate of #29 

Rewriting CSS without the use of Bulma is desired, see referenced issue.
